services:
  - type: web
    name: topic-table-app
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /index.html
    envVars:
      - key: STATE_FILE
        value: /tmp/topic_table_state.json